bookstore_app/config/routes.rb
Rails.application.routes.draw do
  get 'novels/index'
  get 'novels/show'
  get 'novels/new'
  get 'novels/create'
  get 'novels/update'
  get 'novels/edit'
  get 'novels/destroy'
  get 'publishers/index'
  get 'publishers/show'
  get 'publishers/new'
  get 'publishers/create'
  get 'publishers/update'
  get 'publishers/edit'
  get 'publishers/destroy'
  get 'genres/index'
  get 'genres/show'
  get 'genres/new'
  get 'genres/create'
  get 'genres/update'
  get 'genres/edit'
  get 'genres/destroy'
  get 'authors/index'
  get 'authors/show'
  get 'authors/new'
  get 'authors/create'
  get 'authors/update'
  get 'authors/edit'
  get 'authors/destroy'
  get 'static_pages/home'
  root 'static_pages#home'
  get 'static_pages/about'
  get 'static_pages/contact'
  resources :books
  resources :authors
  resources :genres
  resources :publishers
  resources :novels
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

bookstore_app/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

bookstore_app/app/models/book.rb
class Book < ApplicationRecord
end

bookstore_app/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

bookstore_app/app/controllers/books_controller.rb
class BooksController < ApplicationController
	def index 
		@books=Book.all 
	end
	def new

	end
	def create
		#render plain: params[:book] .inspect
		@book=Book.new(book_params)
		@book.save
		redirect_to @book
	end	
	def show
		@book=Book.find(params[:id])
	end	
	private
	def book_params
		params.require(:book).permit(:title, :price, :book_id, :publisher, :description, :number)
	end	
end

bookstore_app/app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def about
  end

  def contact
  end
end

bookstore_app/app/helpers/application_helper.rb
module ApplicationHelper
end

bookstore_app/app/helpers/books_helper.rb
module BooksHelper
end

bookstore_app/app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

bookstore_app/app/views/books/index.html.erb
<div class="container">
<h2> Books Available </h2> 
<table border="1" class="table">
	<tr>
		<th> Book Title </th>
		<th> Book Code </th>
		<th> Book Price </th>
		<th> Publisher </th>
		<th> Book Description </th>
		<th> Book Page </th>
	</tr> 
<% @books.each do |book| %> 
	<tr>
		<td> <%= book.title %> </td> 
		<td> <%= book.book_id %> </td> 
		<td> <%= book.price %> </td> 
		<td> <%= book.publisher %> </td> 
		<td> <%= book.description %> </td> 
		<td> <%= link_to 'Book Page', book_path(book) %> </td> 
	</tr> 
<% end %>
</table>
</div> 

bookstore_app/app/views/books/new.html.erb
<div class="container">
<h1> Add New Book</h1>

<%= form_for :book, url: books_path do |f| %>
<div class="form-group">
<%= f.label :title %>
<%= f.text_field :title %>
</div>
<div class="form-group">
<%= f.label :price %>
<%= f.number_field :price %>
</div>
<div class="form-group">
<%= f.label :book_id %>
<%= f.text_field :book_id %>
</div>
<div class="form-group">
<%= f.label :publisher %>
<%= f.text_field :publisher %>
</div>
<div class="form-group">
<%= f.label :description %>
<%= f.text_area :description %>
</div>
<div class="form-group">
<%= f.submit %>
</div>
<% end %>
</div>

bookstore_app/app/views/books/show.html.erb
<div class="container">

	<h3>Book Details</h3> 

		<p>Book Title: <%= @book.title %> </p> 
		<p>Book Code: <%= @book.book_id %> </p> 
		<p>Book Price: <%= @book.price %> </p> 
		<p>Book Publisher: <%= @book.publisher %> </p> 
		<p>Book Description: <%= @book.description %> </p> 

</div> 

bookstore_app/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
	<head>
		<title>BookstoreApp</title>
		<%= csrf_meta_tags %>
		<%= csp_meta_tag %>

		<%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
		<%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
	</head>     
	<body>
		<div class="container">
			<div class="d-flex flex-column flex-md-row align-items-center p-3 px-md-4 mb-3 bg-white border-bottom shadow-sm">
				<h5 class="my-0 mr-md-auto font-weight-normal"> Sheffield Bookstore </h5>
				<nav class="my-2 my-md-0 mr-md-3">
					<a class="p-2 text-dark" href="#"> <%= link_to "Home", '#' %> </a>
					<a class="p-2 text-dark" href="#"> <%= link_to "About Us", '#' %> </a>
					<a class="p-2 text-dark" href="#"> <%= link_to "Contact Us", '#' %> </a> 
					<a class="p-2 text-dark" href="#"> <%= link_to 'Add New Book', new_book_path %> 
					<a class="p-2 text-dark" href="#"> <%= link_to 'Add New Novel', new_novel_path %> 
					<a class="p-2 text-dark" href="#"> <%= link_to 'View Novel Details', novels_path %> 
					<a class="p-2 text-dark" href="#"> <%= link_to 'Add New Author', new_author_path %> 
					<a class="p-2 text-dark" href="#"> <%= link_to 'Add New Genre', new_genre_path %> 
					<a class="p-2 text-dark" href="#"> <%= link_to 'Add New Publisher', new_publisher_path %> 
					</a> 
				</nav>
			</div>
		</div>
		<div class="container">
			<%= yield %>	
		</div>
	</body>
</html>

bookstore_app/app/views/static_pages/about.html.erb
<h1>StaticPages#about</h1>
<p>Find me in app/views/static_pages/about.html.erb</p>

bookstore_app/app/views/static_pages/contact.html.erb
<h1>StaticPages#contact</h1>
<p>Find me in app/views/static_pages/contact.html.erb</p>

bookstore_app/app/views/static_pages/home.html.erb
<div class="container">
	<h1 class="jumbotron-heading">Album example</h1>
	<div class="container">
		<div class="row">
			<div class="col">
				<p>Mea ei partem atomorum molestiae. Commodo pertinacia expetendis eos an, eam unum praesent in. Usu mollis periculis eu, ad dicat facilisi argumentum vix. In ius choro iuvaret feugiat.</p>
			</div>
			<div class="col">
				<p>Ei eros similique mel, mel eripuit invenire in. Cu eam mollis salutandi. Tamquam recteque vel in, et audire incorrupte mei, an pro saepe nostrum. Sed ea liber pertinacia, impetus lobortis repudiandae mel et, sea ut iisque bonorum.</p>
			</div>
		</div>
	</div>
</div>